"""Add otp_verifications table

Revision ID: 7c9348089156
Revises: 61e6c13ec6be
Create Date: 2025-08-15 19:19:11.827826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9348089156'
down_revision: Union[str, Sequence[str], None] = '61e6c13ec6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('otp_id', sa.UUID(), nullable=False, comment='Unique OTP ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner user ID'),
    sa.Column('otp_code', sa.VARCHAR(length=6), nullable=False, comment='One-time password code'),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='OTP expiry timestamp'),
    sa.Column('verified', sa.BOOLEAN(), nullable=False, comment='Verification status'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation time'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('otp_id')
    )
    op.add_column('fcm_tokens', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'))
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update time'))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_column('fcm_tokens', 'updated_at')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
